import = [
  "~/.config/alacritty/theme-gruvbox.toml"
]

[cursor]
style = "Beam"

[font]
normal = { family = "Inconsolata", style = "Regular" }
bold = { style = "Regular" }
italic = { style = "Regular" }
bold_italic = { style = "Regular" }
size = 16
offset = { x = 0, y = 13 }

[window]
padding = { x = 13, y = 13 }
