alias x="exit"
alias gs="git status"
alias gsh="git show"
alias gd="git diff"
alias gb='git branch '
alias gc='git commit'
alias gcam='git commit -a -m'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias gl='git pull'
alias gp='git push'
alias ll="ls -lh"
alias la="ls -la"
alias rm="trash"
alias gh="git hist"