#!/usr/bin/env zsh

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title warpd-reload
# @raycast.mode compact

. ~/scripts/warpd-reload.zsh

function run() {
  warpdReload
  echo "warpd reloaded"
}

run